# Generated by Django 4.2.26 on 2025-11-27 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_key', models.CharField(db_index=True, max_length=200)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['city_key'], name='weatherapp__city_ke_411d43_idx'), models.Index(fields=['-created_at'], name='weatherapp__created_e900ac_idx')],
            },
        ),
    ]
